### ISSUE TITLE
大佬请教一下如何使用

### ISSUE THREAD

**Issue by xbw12138** [puerts/backend-quickjs#16]
生成build.OHOS.arm64-v8a文件后如何编译出so文件呢引入鸿蒙工程

**Comment by chexiongsheng** [comment]
你是unity？unity直接用unity的plugins，有鸿蒙版，v8和quickjs都有，都真机测试过

**Comment by ruidge** [comment]
> 生成build.OHOS.arm64-v8a文件后如何编译出so文件呢引入鸿蒙工程

鸿蒙能使用吗 ?
